// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClipboardText(arg1) {
  return window['go']['backend']['App']['ClipboardText'](arg1);
}

export function DataListAPI() {
  return window['go']['backend']['App']['DataListAPI']();
}

export function PeerAddAPI(arg1) {
  return window['go']['backend']['App']['PeerAddAPI'](arg1);
}

export function PeerDeleteAPI(arg1) {
  return window['go']['backend']['App']['PeerDeleteAPI'](arg1);
}

export function PeerListAPI() {
  return window['go']['backend']['App']['PeerListAPI']();
}

export function PeerUpdateAPI(arg1, arg2) {
  return window['go']['backend']['App']['PeerUpdateAPI'](arg1, arg2);
}

export function RouteAddAPI(arg1) {
  return window['go']['backend']['App']['RouteAddAPI'](arg1);
}

export function RouteDeleteAPI(arg1) {
  return window['go']['backend']['App']['RouteDeleteAPI'](arg1);
}

export function RouteListAPI() {
  return window['go']['backend']['App']['RouteListAPI']();
}

export function RouteUpdateAPI(arg1, arg2) {
  return window['go']['backend']['App']['RouteUpdateAPI'](arg1, arg2);
}

export function UserAddAPI(arg1) {
  return window['go']['backend']['App']['UserAddAPI'](arg1);
}

export function UserDeleteAPI(arg1) {
  return window['go']['backend']['App']['UserDeleteAPI'](arg1);
}

export function UserListAPI() {
  return window['go']['backend']['App']['UserListAPI']();
}

export function UserUpdateAPI(arg1, arg2) {
  return window['go']['backend']['App']['UserUpdateAPI'](arg1, arg2);
}
